version: "3"

services:
  #swagger:
  #  build:
  #    context: ./api
  #    dockerfile: Dockerfile
  rabit:
    container_name: rabitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"