version: "3.8"

services:
  #swagger:
  #  build:
  #    context: ./api
  #    dockerfile: Dockerfile
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mailing
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    container_name: api
    ports: 
      - "9000:9000"
    build: .

volumes:
  db-data: