version: "3.8"

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${NAMEDB}
      MYSQL_USER: ${USERDB}
      MYSQL_PASSWORD: ${PASSDB}
    ports:
      - "3306:3306"
    networks: 
      - backend

  app:
    depends_on:
      - db
      - rabbit
    container_name: api
    ports: 
      - "9000:9000"
    restart: on-failure
    build: 
      context: ./
      dockerfile: docker/Dockerfile-api
    networks: 
      - backend
  
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - backend
    
  consumer:
    depends_on:
      - db
      - rabbit
    restart: on-failure
    container_name: consumer
    build: 
      context: ./
      dockerfile: docker/Dockerfile-consumer
    ports:
      - "9001:9000"
    networks: 
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: "bridge"