name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  pre-build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          working-directory: api/controllers

